# Generated by Django 5.0.7 on 2024-07-31 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_item_policies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Policies",
            new_name="Politics",
        ),
    ]
