# Generated by Django 5.0.7 on 2024-07-31 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_policies_politics"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Politics",
            new_name="Politices",
        ),
    ]
