# Generated by Django 5.0.7 on 2024-07-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="description",
            new_name="message",
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
