# Generated by Django 5.0.7 on 2024-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_units_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="units",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="app.units"
            ),
        ),
    ]
