# Generated by Django 5.0.7 on 2024-07-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_services_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="politices",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
