# Generated by Django 5.0.7 on 2024-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_politices_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="units",
        ),
        migrations.AddField(
            model_name="units",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="units", to="app.services"
            ),
        ),
    ]
