# Generated by Django 5.0.7 on 2024-08-01 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_services_units_alter_units_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="units",
            name="services",
        ),
    ]
