# Generated by Django 5.0.7 on 2024-08-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_remove_units_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="units",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="services_set",
                related_query_name="service",
                to="app.services",
            ),
        ),
    ]
